### ISSUE TITLE
Error="getting Frame 2: Frame, frame_000000001, Not Found"

### ISSUE THREAD

**Issue by Maxime2** [Fantom-foundation/go-lachesis#138]
I am running 3 node lachesis from the master branch and sometimes (not on every run) getting the following error:
```
time="2019-01-31T09:38:53+11:00" level=error msg="c.poset.ProcessDecidedRounds()" Error="getting Frame 2: Frame, frame_000000001, Not Found" id=18316840364296702241 z_trace="goroutine 710 [running]:
github.com/Fantom-foundation/go-lachesis/src/log.(*Hook).Fire(0xc0001cc360, 0xc010813080, 0x0, 0x0)
         /home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/log/hook.go:97 +0x18f
github.com/Fantom-foundation/go-lachesis/vendor/github.com/sirupsen/logrus.LevelHooks.Fire(0xc000147b60, 0x2, 0xc010813080, 0x1e7be52cb270, 0xc02e33d8c5)
         /home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/github.com/sirupsen/logrus/hooks.go:28 +0x91
github.com/Fantom-foundation/go-lachesis/vendor/github.com/sirupsen/logrus.(*Entry).fireHooks(0xc010813080)
         /home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/github.com/sirupsen/logrus/entry.go:234 +0x8c
github.com/Fantom-foundation/go-lachesis/vendor/github.com/sirupsen/logrus.Entry.log(0xc000144ba0, 0xc01082f0b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
         /home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/github.com/sirupsen/logrus/entry.go:212 +0xf6
github.com/Fantom-foundation/go-lachesis/vendor/github.com/sirupsen/logrus.(*Entry).Log(0xc010813020, 0x2, 0xc010245a98, 0x1, 0x1)
         /home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/github.com/sirupsen/logrus/entry.go:256 +0xb7
github.com/Fantom-foundation/go-lachesis/vendor/github.com/sirupsen/logrus.(*Entry).Error(0xc010813020, 0xc010245a98, 0x1, 0x1)
         /home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/github.com/sirupsen/logrus/entry.go:285 +0x51
github.com/Fantom-foundation/go-lachesis/src/node.(*Core).RunConsensus(0xc000249560, 0xc311e6205, 0x13dcbe0)
         /home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/node/core.go:561 +0x810
github.com/Fantom-foundation/go-lachesis/src/node.(*Node).sync(0xc0001f4690, 0xc0103f0900, 0xb, 0xd, 0xc00ff58658, 0x8)
         /home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/node/node.go:615 +0x1b4
github.com/Fantom-foundation/go-lachesis/src/node.(*Node).processEagerSyncRequest(0xc0001f4690, 0xc0107da4b0, 0xc010758780)
         /home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/node/node.go:335 +0x26e
github.com/Fantom-foundation/go-lachesis/src/node.(*Node).processRPC(0xc0001f4690, 0xc0107da4b0)
         /home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/node/node.go:261 +0x1ea
github.com/Fantom-foundation/go-lachesis/src/node.(*Node).lachesis.func1()
         /home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/node/node.go:230 +0xa2
github.com/Fantom-foundation/go-lachesis/src/node.(*nodeState2).goFunc.func1(0xc000080740, 0xc010758da0)
         /home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/node/state.go:70 +0x5b
created by github.com/Fantom-foundation/go-lachesis/src/node.(*nodeState2).goFunc
         /home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/node/state.go:65 +0x49
"
```

The error seems happens in ApplyInternalTransactions() function introduced in pull-request #137 as additional debug output shows.

```
time="2019-01-31T09:38:53+11:00" level=warning msg="** Making Frame @ round received: 2" id=18316840364296702241
time="2019-01-31T09:38:53+11:00" level=warning msg="** MakeFRame p.ApplyInternalTransactions err: Frame, frame_000000001, Not Found" id=18316840364296702241
time="2019-01-31T09:38:53+11:00" level=error msg="c.poset.ProcessDecidedRounds()" Error="getting Frame 2: Frame, frame_000000001, Not Found" id=18316840364296702241 z_trace="goroutine 710 [running]:\ngithub.com/Fantom-foundation/go-lachesis/src/log.(*Hook).Fire(0xc0001cc360, 0xc010813080, 0x0, 0x0)\n\t/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/log/hook.go:97 +0x18f\ngithub.com/Fantom-foundation/go-lachesis/vendor/github.com/sirupsen/logrus.LevelHooks.Fire(0xc000147b60, 0x2, 0xc010813080, 0x1e7be52cb270, 0xc02e33d8c5)\n\t/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/github.com/sirupsen/logrus/hooks.go:28 +0x91\ngithub.com/Fantom-foundation/go-lachesis/vendor/github.com/sirupsen/logrus.(*Entry).fireHooks(0xc010813080)\n\t/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/github.com/sirupsen/logrus/entry.go:234 +0x8c\ngithub.com/Fantom-foundation/go-lachesis/vendor/github.com/sirupsen/logrus.Entry.log(0xc000144ba0, 0xc01082f0b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/github.com/sirupsen/logrus/entry.go:212 +0xf6\ngithub.com/Fantom-foundation/go-lachesis/vendor/github.com/sirupsen/logrus.(*Entry).Log(0xc010813020, 0x2, 0xc010245a98, 0x1, 0x1)\n\t/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/github.com/sirupsen/logrus/entry.go:256 +0xb7\ngithub.com/Fantom-foundation/go-lachesis/vendor/github.com/sirupsen/logrus.(*Entry).Error(0xc010813020, 0xc010245a98, 0x1, 0x1)\n\t/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/github.com/sirupsen/logrus/entry.go:285 +0x51\ngithub.com/Fantom-foundation/go-lachesis/src/node.(*Core).RunConsensus(0xc000249560, 0xc311e6205, 0x13dcbe0)\n\t/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/node/core.go:561 +0x810\ngithub.com/Fantom-foundation/go-lachesis/src/node.(*Node).sync(0xc0001f4690, 0xc0103f0900, 0xb, 0xd, 0xc00ff58658, 0x8)\n\t/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/node/node.go:615 +0x1b4\ngithub.com/Fantom-foundation/go-lachesis/src/node.(*Node).processEagerSyncRequest(0xc0001f4690, 0xc0107da4b0, 0xc010758780)\n\t/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/node/node.go:335 +0x26e\ngithub.com/Fantom-foundation/go-lachesis/src/node.(*Node).processRPC(0xc0001f4690, 0xc0107da4b0)\n\t/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/node/node.go:261 +0x1ea\ngithub.com/Fantom-foundation/go-lachesis/src/node.(*Node).lachesis.func1()\n\t/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/node/node.go:230 +0xa2\ngithub.com/Fantom-foundation/go-lachesis/src/node.(*nodeState2).goFunc.func1(0xc000080740, 0xc010758da0)\n\t/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/node/state.go:70 +0x5b\ncreated by github.com/Fantom-foundation/go-lachesis/src/node.(*nodeState2).goFunc\n\t/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/node/state.go:65 +0x49\n"
```

I am using the following command to run 3-node lachesis:
```
n=3 entry=main logshold=-1,-1,-1,85,0,0 BUILD_DIR="$PWD" ./scripts/multi.bash
```

The patch adding more debug output is bellow:
```
diff --git a/src/poset/poset.go b/src/poset/poset.go
index 8b5a368..2cf4281 100644
--- a/src/poset/poset.go
+++ b/src/poset/poset.go
@@ -10,11 +10,11 @@ import (
 	"sort"
 	"sync"
 
-	"github.com/hashicorp/golang-lru"
+	lru "github.com/hashicorp/golang-lru"
 	"github.com/sirupsen/logrus"
 
 	"github.com/Fantom-foundation/go-lachesis/src/common"
-	"github.com/Fantom-foundation/go-lachesis/src/log"
+	lachesis_log "github.com/Fantom-foundation/go-lachesis/src/log"
 	"github.com/Fantom-foundation/go-lachesis/src/peers"
 	"github.com/Fantom-foundation/go-lachesis/src/state"
 )
@@ -1363,6 +1363,7 @@ func (p *Poset) GetFrame(roundReceived int64) (Frame, error) {
 	// Try to get it from the Store first
 	frame, err := p.Store.GetFrame(roundReceived)
 	if err == nil || !common.Is(err, common.KeyNotFound) {
+		p.logger.Warnf("** p.Store.GetFrame err: %v", err)
 		return frame, err
 	}
 	// otherwise make new
@@ -1372,8 +1373,10 @@ func (p *Poset) GetFrame(roundReceived int64) (Frame, error) {
 // MakeFrame computes the Frame corresponding to a RoundReceived.
 func (p *Poset) MakeFrame(roundReceived int64) (Frame, error) {
 	// Get the Round and corresponding consensus Events
+	p.logger.Warnf("** Making Frame @ round received: %d", roundReceived)
 	round, err := p.Store.GetRoundReceived(roundReceived)
 	if err != nil {
+		p.logger.Warnf("** MakeFrame pStore.GetRoundReceived err: %v", err)
 		return Frame{}, err
 	}
 
@@ -1383,6 +1386,7 @@ func (p *Poset) MakeFrame(roundReceived int64) (Frame, error) {
 		hash.Set(eh)
 		e, err := p.Store.GetEventBlock(hash)
 		if err != nil {
+			p.logger.Warnf("** MakeFrame p.Store.GetEventBlock err: %v", err)
 			return Frame{}, err
 		}
 		events = append(events, e)
@@ -1392,6 +1396,7 @@ func (p *Poset) MakeFrame(roundReceived int64) (Frame, error) {
 
 	stateHash, err := p.ApplyInternalTransactions(roundReceived, events)
 	if err != nil {
+		p.logger.Warnf("** MakeFRame p.ApplyInternalTransactions err: %v", err)
 		return Frame{}, err
 	}
 
@@ -1404,6 +1409,7 @@ func (p *Poset) MakeFrame(roundReceived int64) (Frame, error) {
 		if _, ok := roots[c]; !ok {
 			root, err := p.createRoot(ev)
 			if err != nil {
+				p.logger.Warnf("** MakeFrame p.createRoot err: %v", err)
 				return Frame{}, err
 			}
 			roots[ev.GetCreator()] = root
@@ -1424,6 +1430,7 @@ func (p *Poset) MakeFrame(roundReceived int64) (Frame, error) {
 			var root Root
 			lastConsensusEventHash, isRoot, err := p.Store.LastConsensusEventFrom(peer)
 			if err != nil {
+				p.logger.Warnf("** MakeFRame p.Store.LastConsensusEventFrom err: %v", err)
 				return Frame{}, err
 			}
 			if isRoot {
@@ -1431,10 +1438,12 @@ func (p *Poset) MakeFrame(roundReceived int64) (Frame, error) {
 			} else {
 				lastConsensusEvent, err := p.Store.GetEventBlock(lastConsensusEventHash)
 				if err != nil {
+					p.logger.Warnf("** MakeFrame p.Store.GetEventBlock err: %v", err)
 					return Frame{}, err
 				}
 				root, err = p.createRoot(lastConsensusEvent)
 				if err != nil {
+					p.logger.Warnf("** MakeFrame p.createRoot 2 err:", err)
 					return Frame{}, err
 				}
 			}
@@ -1460,6 +1469,7 @@ func (p *Poset) MakeFrame(roundReceived int64) (Frame, error) {
 				if !selfParent.Equal(roots[ev.GetCreator()].SelfParent.Hash) {
 					other, err := p.createOtherParentRootEvent(ev)
 					if err != nil {
+						p.logger.Warnf("** MakeFrame p.createOtherParentRootEvent err:%v", err)
 						return Frame{}, err
 					}
 					roots[ev.GetCreator()].Others[hash.String()] = &other
@@ -1485,6 +1495,7 @@ func (p *Poset) MakeFrame(roundReceived int64) (Frame, error) {
 	}
 
 	if err := p.Store.SetFrame(res); err != nil {
+		p.logger.Warnf("** MakeFrame p.Store.SetFrame err:", err)
 		return Frame{}, err
 	}
 
```

**Comment by devintegral** [comment]
This error is about next frame creating before previous. It was happening silently before PR, we get it checked with this PR.
PR is a preparing stage to proof-of-work implementation. Poset will be fixed in the nexts.

**Comment by SamuelMarks** [comment]
@devintegral What's the ETA on these fixes?

**Comment by devintegral** [comment]
outdated
