### ISSUE TITLE
goroutine leaks in TestDiscoveryPeer and TestDiscoveryHost

### ISSUE THREAD

**Issue by Maxime2** [Fantom-foundation/go-lachesis#211]
**Describe the bug**
Some gRPC threads are left running after TestDiscoveryPeer and TestDiscoveryHost tests terminates:
```
--- FAIL: TestDiscoveryPeer (30.12s)
    leaktest.go:162: leaktest: context canceled
    leaktest.go:168: leaktest: leaked goroutine: goroutine 55 [select]:
        github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc0001f8b00)
        	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:115 +0x204
        created by github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.newCCBalancerWrapper
        	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:106 +0x2ba
    leaktest.go:168: leaktest: leaked goroutine: goroutine 56 [select]:
        github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc0000bc840)
        	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/clientconn.go:1058 +0x4cf
        created by github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.(*addrConn).connect
        	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/clientconn.go:767 +0xfc
--- FAIL: TestDiscoveryHost (1.27s)
    leaktest.go:162: leaktest: context canceled
    leaktest.go:168: leaktest: leaked goroutine: goroutine 24 [select]:
        github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc0002a4000)
        	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/clientconn.go:1058 +0x4cf
        created by github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.(*addrConn).connect
        	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/clientconn.go:767 +0xfc
    leaktest.go:168: leaktest: leaked goroutine: goroutine 95 [select]:
        github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc0002d6600)
        	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:115 +0x204
        created by github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.newCCBalancerWrapper
        	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:106 +0x2ba
    leaktest.go:168: leaktest: leaked goroutine: goroutine 96 [select]:
        github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc0000bd340)
        	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/clientconn.go:1058 +0x4cf
        created by github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.(*addrConn).connect
        	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/clientconn.go:767 +0xfc
    leaktest.go:168: leaktest: leaked goroutine: goroutine 150 [select]:
        github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000020c00)
        	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:115 +0x204
        created by github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.newCCBalancerWrapper
        	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:106 +0x2ba
FAIL
FAIL	github.com/Fantom-foundation/go-lachesis/src/posnode	31.594s
```

**To Reproduce**
1. Apply patch:
```
diff --git a/src/posnode/discovery_test.go b/src/posnode/discovery_test.go
index 9719f5f6..10f0c13e 100644
--- a/src/posnode/discovery_test.go
+++ b/src/posnode/discovery_test.go
@@ -8,9 +8,12 @@ import (
 
        "github.com/Fantom-foundation/go-lachesis/src/crypto"
        "github.com/Fantom-foundation/go-lachesis/src/hash"
+       "github.com/fortytw2/leaktest"
 )
 
 func TestDiscoveryPeer(t *testing.T) {
+    defer leaktest.CheckTimeout(t, 30 * time.Second)()
+
        // node 1
        store1 := NewMemStore()
        node1 := NewForTests("node1", store1, nil)
@@ -72,6 +75,8 @@ func TestDiscoveryPeer(t *testing.T) {
 }
 
 func TestDiscoveryHost(t *testing.T) {
+    defer leaktest.CheckTimeout(t, time.Second)()
+
        assertar := assert.New(t)
 
        // node 1
```
2. run `make test 2>&1 | tee 00-tests.log`

**Expected behavior**
gRPC layer should be shotdown properly so no leaked goroutines left.

**Comment by devintegral** [comment]
outdated
