### ISSUE TITLE
goroutine leaks in TestGRPC

### ISSUE THREAD

**Issue by Maxime2** [Fantom-foundation/go-lachesis#212]
**Describe the bug**
Some gRPC threads are left running after TestGRPC/over_TCP and TestGRPC/over_Fake test finish:
```
--- FAIL: TestGRPC (60.07s)
    --- FAIL: TestGRPC/over_TCP (30.04s)
        wire.go:37: service start at [::]:35527
        leaktest.go:162: leaktest: context canceled
        leaktest.go:168: leaktest: leaked goroutine: goroutine 25 [select]:
            github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc0000205c0)
            	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:115 +0x204
            created by github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.newCCBalancerWrapper
            	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:106 +0x2ba
        leaktest.go:168: leaktest: leaked goroutine: goroutine 26 [select]:
            github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc0000e62c0)
            	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/clientconn.go:1058 +0x4cf
            created by github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.(*addrConn).connect
            	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/clientconn.go:767 +0xfc
        leaktest.go:168: leaktest: leaked goroutine: goroutine 55 [select]:
            github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000021100)
            	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:115 +0x204
            created by github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.newCCBalancerWrapper
            	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:106 +0x2ba
        leaktest.go:168: leaktest: leaked goroutine: goroutine 56 [select]:
            github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc0000e6dc0)
            	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/clientconn.go:1058 +0x4cf
            created by github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.(*addrConn).connect
            	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/clientconn.go:767 +0xfc
    --- FAIL: TestGRPC/over_Fake (30.04s)
        wire.go:37: service start at server.fake:0
        leaktest.go:162: leaktest: context canceled
        leaktest.go:168: leaktest: leaked goroutine: goroutine 97 [select]:
            github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000274240)
            	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:115 +0x204
            created by github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.newCCBalancerWrapper
            	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:106 +0x2ba
        leaktest.go:168: leaktest: leaked goroutine: goroutine 157 [select]:
            github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc0000e6840)
            	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/clientconn.go:1058 +0x4cf
            created by github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.(*addrConn).connect
            	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/clientconn.go:767 +0xfc
        leaktest.go:168: leaktest: leaked goroutine: goroutine 198 [select]:
            github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc0002248c0)
            	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:115 +0x204
            created by github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.newCCBalancerWrapper
            	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:106 +0x2ba
        leaktest.go:168: leaktest: leaked goroutine: goroutine 214 [select]:
            github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc0003c2000)
            	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/clientconn.go:1058 +0x4cf
            created by github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc.(*addrConn).connect
            	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/vendor/google.golang.org/grpc/clientconn.go:767 +0xfc
FAIL
FAIL	github.com/Fantom-foundation/go-lachesis/src/posnode/api	60.180s
```

**To Reproduce**
1. Apply the patch:
```
diff --git a/src/posnode/api/wire_test.go b/src/posnode/api/wire_test.go
index 682c8c1c..aa092c87 100644
--- a/src/posnode/api/wire_test.go
+++ b/src/posnode/api/wire_test.go
@@ -3,6 +3,7 @@ package api
 import (
        "context"
        "testing"
+       "time"
 
        "github.com/golang/mock/gomock"
        "github.com/stretchr/testify/assert"
@@ -12,6 +13,7 @@ import (
        "github.com/Fantom-foundation/go-lachesis/src/hash"
        "github.com/Fantom-foundation/go-lachesis/src/inter/wire"
        "github.com/Fantom-foundation/go-lachesis/src/network"
+       "github.com/fortytw2/leaktest"
 )
 
 // gen is an empty genesis hash.
@@ -31,6 +33,8 @@ func TestGRPC(t *testing.T) {
 }
 
 func testGRPC(t *testing.T, bind, from string, listen network.ListenFunc, opts ...grpc.DialOption) {
+    defer leaktest.CheckTimeout(t, 30 * time.Second)()
+
        ctrl := gomock.NewController(t)
        defer ctrl.Finish()
 
```
2. run `make test 2>&1 | tee 00-tests.log`

**Expected behavior**
gRPC layer should be shotdown properly so no leaked goroutines left.

**Comment by devintegral** [comment]
outdated
