### ISSUE TITLE
TestGrpcAppCalls: Sporadic data race and panic: send on closed channel

### ISSUE THREAD

**Issue by Maxime2** [Fantom-foundation/go-lachesis#231]
**Describe the bug**
Periodically the following crash occurs in `TestGrpcAppCalls`:
```
==================
WARNING: DATA RACE
Write at 0x00c000328250 by goroutine 54:
  runtime.closechan()
      /usr/local/go/src/runtime/chan.go:334 +0x0
  github.com/Fantom-foundation/go-lachesis/src/proxy.(*grpcLachesisProxy).Close()
      /home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/proxy/grpc_lachesis.go:94 +0xbe
  github.com/Fantom-foundation/go-lachesis/src/proxy.testGrpcAppCalls()
      /home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/proxy/grpc_app_test.go:144 +0x81b
  github.com/Fantom-foundation/go-lachesis/src/proxy.TestGrpcAppCalls.func2()
      /home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/proxy/grpc_app_test.go:24 +0xa7
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:865 +0x163

Previous read at 0x00c000328250 by goroutine 60:
  runtime.chansend()
      /usr/local/go/src/runtime/chan.go:142 +0x0
  github.com/Fantom-foundation/go-lachesis/src/proxy.(*grpcLachesisProxy).listenEvents()
      /home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/proxy/grpc_lachesis.go:239 +0x879

Goroutine 54 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:916 +0x699
  github.com/Fantom-foundation/go-lachesis/src/proxy.TestGrpcAppCalls()
      /home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/proxy/grpc_app_test.go:22 +0x8c
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:865 +0x163

Goroutine 60 (running) created at:
  github.com/Fantom-foundation/go-lachesis/src/proxy.NewGrpcLachesisProxy()
      /home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/proxy/grpc_lachesis.go:83 +0x717
  github.com/Fantom-foundation/go-lachesis/src/proxy.testGrpcAppCalls()
      /home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/proxy/grpc_app_test.go:55 +0x451
  github.com/Fantom-foundation/go-lachesis/src/proxy.TestGrpcAppCalls.func2()
      /home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/proxy/grpc_app_test.go:24 +0xa7
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:865 +0x163
==================
panic: send on closed channel

goroutine 274 [running]:
github.com/Fantom-foundation/go-lachesis/src/proxy.(*grpcLachesisProxy).listenEvents(0xc00026a180)
	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/proxy/grpc_lachesis.go:239 +0x87a
created by github.com/Fantom-foundation/go-lachesis/src/proxy.NewGrpcLachesisProxy
	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/proxy/grpc_lachesis.go:83 +0x718
FAIL	github.com/Fantom-foundation/go-lachesis/src/proxy	9.879s
```

**To Reproduce**
Steps to reproduce the behaviour:
The report above has been obtained on the commit `2e93b836fc156aaa2d8e0674bc0ac42be5f2787f` executing the following command: `TESTCOUNT=2 make test 2>&1 | tee 00-tests.log`, however, this bug occurs not on every run of the test suite.

**Expected behaviour**
Implementation of `grpcLachesisProxy` must ensure safe shutdown on Close() method execution.

**Comment by Maxime2** [comment]
`panic: send on closed channel` still appears in current master; happens as well in coverage testing: `make coverage` or
```
$ TESTCOUNT=1 make coverage 2>&1 | tee 00-tests.log
```

The [log for travis job](https://api.travis-ci.org/v3/job/546545223/log.txt) is as follow
```
panic: send on closed channel

goroutine 57 [running]:
github.com/Fantom-foundation/go-lachesis/src/proxy.(*grpcLachesisProxy).listenEvents(0xc00039c100)
	/home/travis/gopath/src/github.com/Fantom-foundation/go-lachesis/src/proxy/grpc_lachesis.go:234 +0x720
created by github.com/Fantom-foundation/go-lachesis/src/proxy.NewGrpcLachesisProxy
	/home/travis/gopath/src/github.com/Fantom-foundation/go-lachesis/src/proxy/grpc_lachesis.go:78 +0x42e
FAIL	github.com/Fantom-foundation/go-lachesis/src/proxy	3.065s
```

**Comment by devintegral** [comment]
outdated
