### ISSUE TITLE
TestPosetTxn: sporadic panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Maxime2** [Fantom-foundation/go-lachesis#232]
**Describe the bug**
Periodically test suite fails with the following crash in `TestPosetTxn`:
```
--- FAIL: TestPosetTxn (0.15s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb5d66b]

goroutine 52 [running]:
testing.tRunner.func1(0xc000478300)
	/usr/local/go/src/testing/testing.go:830 +0x68a
panic(0xc107e0, 0x1289730)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/Fantom-foundation/go-lachesis/src/posposet.(*Poset).FrameOfEvent(0xc000d3a4e0, 0xe6c4c08aa17b5173, 0xbd041819405d21c, 0x43dad6e5b5e60515, 0x6607690d01288867, 0xc000ad4a00, 0x1)
	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/posposet/frames.go:55 +0xfb
github.com/Fantom-foundation/go-lachesis/src/posposet.(*Poset).collectParents(0xc000d3a4e0, 0xc000219710, 0xc000774f08, 0xc000774f20)
	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/posposet/poset.go:348 +0x1f7
github.com/Fantom-foundation/go-lachesis/src/posposet.(*Poset).collectParents(0xc000d3a4e0, 0xc000219700, 0xc000774f08, 0xc000774f20)
	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/posposet/poset.go:357 +0x45e
github.com/Fantom-foundation/go-lachesis/src/posposet.(*Poset).collectParents(0xc000d3a4e0, 0xc0002196f0, 0xc000774f08, 0xc000774f20)
	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/posposet/poset.go:357 +0x45e
github.com/Fantom-foundation/go-lachesis/src/posposet.(*Poset).collectParents(0xc000d3a4e0, 0xc0002196e0, 0xc000774f08, 0xc000774f20)
	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/posposet/poset.go:357 +0x45e
github.com/Fantom-foundation/go-lachesis/src/posposet.(*Poset).collectParents(0xc000d3a4e0, 0xc0002196c0, 0xc000774f08, 0xc000774f20)
	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/posposet/poset.go:357 +0x45e
github.com/Fantom-foundation/go-lachesis/src/posposet.(*Poset).collectParents(0xc000d3a4e0, 0xc0002196b0, 0xc000774f08, 0xc000774f20)
	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/posposet/poset.go:357 +0x45e
github.com/Fantom-foundation/go-lachesis/src/posposet.(*Poset).collectParents(0xc000d3a4e0, 0xc000219610, 0xc000774f08, 0xc000774f20)
	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/posposet/poset.go:357 +0x45e
github.com/Fantom-foundation/go-lachesis/src/posposet.(*Poset).topologicalOrdered(0xc000d3a4e0, 0x6, 0xcc4e95, 0x2a, 0xc000775220)
	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/posposet/poset.go:328 +0x629
github.com/Fantom-foundation/go-lachesis/src/posposet.(*Poset).consensus(0xc000d3a4e0, 0xc00013d360)
	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/posposet/poset.go:119 +0x4ed
github.com/Fantom-foundation/go-lachesis/src/inter/ordering.EventBuffer.func1(0xc0001b0350)
	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/inter/ordering/event_buffer.go:77 +0x97e
github.com/Fantom-foundation/go-lachesis/src/inter/ordering.EventBuffer.func1(0xc0002182d0)
	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/inter/ordering/event_buffer.go:84 +0xdc1
github.com/Fantom-foundation/go-lachesis/src/inter/ordering.EventBuffer.func2(0xc00014bb80)
	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/inter/ordering/event_buffer.go:102 +0x3c1
github.com/Fantom-foundation/go-lachesis/src/posposet.MakeOrderedInput.func3(0xc00014bb80)
	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/posposet/common_test.go:52 +0x47
github.com/Fantom-foundation/go-lachesis/src/posposet.(*Poset).PushEventSync(0xc000d3a4e0, 0xa3d5a8fa69eb19d0, 0xda0c6b44dcf5cf1b, 0x62ae99b47d91c884, 0x615545d6578e32dd)
	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/posposet/poset_test.go:100 +0xb8
github.com/Fantom-foundation/go-lachesis/src/posposet.TestPosetTxn(0xc000478300)
	/home/maxime/go/src/github.com/Fantom-foundation/go-lachesis/src/posposet/transaction_test.go:44 +0x5a7
testing.tRunner(0xc000478300, 0xd1a130)
	/usr/local/go/src/testing/testing.go:865 +0x164
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x69a
FAIL	github.com/Fantom-foundation/go-lachesis/src/posposet	17.503s
```

**To Reproduce**
The test failure above has been obtained executing the following command: `TESTCOUNT=2 make test 2>&1 | tee 00-tests.log` , however this issue occurs not on every run of the test suite.

**Expected behavior**
Test suite should be executed without any issue on every run.

**Comment by Maxime2** [comment]
The log file in full: [00-tests-4.log](https://github.com/Fantom-foundation/go-lachesis/files/3284958/00-tests-4.log)

**Comment by devintegral** [comment]
outdated
