### ISSUE TITLE
Unknown wevent.Body.CreatorID=0

### ISSUE THREAD

**Issue by Maxime2** [Fantom-foundation/go-lachesis#75]
**Describe the bug**
When I set cache size to 100 for lachesis store with the flag --cache-size=100 I get bunch of the following errors:

```
goroutine 11078 [running]:
runtime/debug.Stack(0xc058e660c0, 0xc111e85a68, 0x42bbb2)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/andrecronje/lachesis/src/log.(*Hook).Fire(0xc000340120, 0xc0593fac00, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/andrecronje/lachesis/src/log/hook.go:96 +0x133
github.com/andrecronje/lachesis/vendor/github.com/sirupsen/logrus.LevelHooks.Fire(0xc00013d230, 0x2, 0xc0593fac00, 0x476be466517f, 0xc015cad9f5)
        /home/ubuntu/go/src/github.com/andrecronje/lachesis/vendor/github.com/sirupsen/logrus/hooks.go:28 +0x91
github.com/andrecronje/lachesis/vendor/github.com/sirupsen/logrus.(*Entry).fireHooks(0xc0593fac00)
        /home/ubuntu/go/src/github.com/andrecronje/lachesis/vendor/github.com/sirupsen/logrus/entry.go:223 +0x8c
github.com/andrecronje/lachesis/vendor/github.com/sirupsen/logrus.Entry.log(0xc00007c780, 0xc0eff61170, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/go/src/github.com/andrecronje/lachesis/vendor/github.com/sirupsen/logrus/entry.go:201 +0xf6
github.com/andrecronje/lachesis/vendor/github.com/sirupsen/logrus.(*Entry).Error(0xc0593fa7e0, 0xc111e85d38, 0x1, 0x1)
        /home/ubuntu/go/src/github.com/andrecronje/lachesis/vendor/github.com/sirupsen/logrus/entry.go:277 +0xae
github.com/andrecronje/lachesis/src/node.(*Node).processEagerSyncRequest(0xc058ec82a0, 0xbf3400, 0xc071bbf480, 0x0, 0x0, 0xc059a8a300, 0xc071bbf480)
        /home/ubuntu/go/src/github.com/andrecronje/lachesis/src/node/node.go:304 +0x322
github.com/andrecronje/lachesis/src/node.(*Node).processRPC(0xc058ec82a0, 0xbf3400, 0xc071bbf480, 0x0, 0x0, 0xc059a8a300)
        /home/ubuntu/go/src/github.com/andrecronje/lachesis/src/node/node.go:227 +0x1e8
github.com/andrecronje/lachesis/src/node.(*Node).lachesis.func1()
        /home/ubuntu/go/src/github.com/andrecronje/lachesis/src/node/node.go:204 +0xa6
github.com/andrecronje/lachesis/src/node.(*nodeState).goFunc.func1(0xc058ec82a0, 0xc14c5b4340)
        /home/ubuntu/go/src/github.com/andrecronje/lachesis/src/node/state.go:53 +0x53
created by github.com/andrecronje/lachesis/src/node.(*nodeState).goFunc
        /home/ubuntu/go/src/github.com/andrecronje/lachesis/src/node/state.go:51 +0x66
time="2018-11-08T04:13:12Z" level=error msg="n.sync(cmd.Events)" error="Unknown wevent.Body.CreatorID=0" this_id=855157020


```
There no such errors with default value of cache size (500).

**To Reproduce**
1. Add --cache-size=100 switch to lachesis run switches in scripts/multi_run.bash
2. Run multi-node lachesis: 
`n=7 entry=main logshold=-1,-1,-1,85,0,0 BUILD_DIR="$PWD" ./scripts/multi.bash`
3. wait until these errors appear

- OS: Ubuntu 18.04
- lachesis at  d474e0396ac23153d783f75aea2cc6debb3cabaf

**Comment by devintegral** [comment]
outdated
